# k8s/overlays/production/kustomization.yaml
# Production overlay

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django-production

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

resources:
  - hpa.yaml
  - network-policy.yaml

commonLabels:
  environment: production

replicas:
  - name: django
    count: 3
  - name: nginx
    count: 2

images:
  - name: YOUR_REGISTRY/django
    newTag: latest
