# k8s/overlays/staging/kustomization.yaml
# Staging overlay

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: safarichap-staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

resources:
  - hpa.yaml

commonLabels:
  environment: staging

replicas:
  - name: django
    count: 2
  - name: nginx
    count: 2
